### ISSUE TITLE
57 Template that are valid

### ISSUE THREAD

**Issue by Sicks3c** [topscoder/nuclei-wordfence-cve#10]
Hello

it appears that 57 templates are valid when following the installation 
<img width="564" alt="Screenshot 2023-07-19 at 14 05 10" src="https://github.com/topscoder/nuclei-wordfence-cve/assets/32225186/52d0a393-256c-48dc-a26e-1127f4c06870">

Cheers

**Comment by topscoder** [comment]
![Scherm­afbeelding 2023-07-22 om 12 28 12](https://github.com/topscoder/nuclei-wordfence-cve/assets/86197446/7351b8e5-3be7-4774-850d-9a51fbb8a7b5)

Fixed ✅

**Comment by topscoder** [comment]
![Scherm­afbeelding 2023-07-22 om 12 28 12](https://github.com/topscoder/nuclei-wordfence-cve/assets/86197446/7351b8e5-3be7-4774-850d-9a51fbb8a7b5)

Fixed ✅

**Comment by Sicks3c** [comment]
I ran the same command after a git pull
<img width="1432" alt="Screenshot 2023-07-23 at 13 09 29" src="https://github.com/topscoder/nuclei-wordfence-cve/assets/32225186/25c5dbc4-9add-4c10-a5f1-07212cd94b43">

**Comment by topscoder** [comment]
What Nuclei version are you running? And please try this command after being sure you’re at Nuclei v2.9.9;
‘Nuclei -t GitHub/nuclei-wordfence-cve -u https://www.google.com -validate’

**Comment by topscoder** [comment]
To me it looks like an issue with Nuclei being confused. 

Try to remove the templates and reinstall. I believe Nuclei changed something in the paths for GitHub repos.

Remove the templates:
```
rm -Rf ~/nuclei-templates/GitHub/nuclei-wordfence-cve
```

Reinstall a fresh copy using Nuclei:
```
export GITHUB_TEMPLATE_REPO=topscoder/nuclei-wordfence-cve
nuclei -update
nuclei -update-templates
```

And run validation again to verify if it's been fixed:
```
nuclei -t github/nuclei-wordfence-cve-topscoder -u https://www.google.com -validate
```

**Comment by Sicks3c** [comment]
Hey 

This seems to have worked
<img width="734" alt="Screenshot 2023-07-23 at 16 19 22" src="https://github.com/topscoder/nuclei-wordfence-cve/assets/32225186/6a90a508-0c38-4f61-a696-a9cc3e2f3bfc">
