### ISSUE TITLE
FP: lazy load plugin

### ISSUE THREAD

**Issue by joostgrunwald** [topscoder/nuclei-wordfence-cve#14]
dsl:
          - compare_versions(version, '<= 0.6.1')

The check hits on version 0.6.1, while this is the fixed version.
source: https://www.acunetix.com/vulnerabilities/web/lazy-load-cross-site-scripting-0-6/

**Comment by topscoder** [comment]
Thanks for reporting @joostgrunwald !

**Comment by joostgrunwald** [comment]
This seems to be a more frequent issue in the nuclei set, maybe CVE --> Parse NVD api for CVE query --> get exact bounds --> adjust template for that automatically. Could be a good addition in the future, would do it myself if I had the time :)

**Comment by topscoder** [comment]
Could you send some of the problematic ones? I will check if it is a bug in the code or in the wordfence API. I like to stick to a single source of truth to avoid unnecessary complexity.
