### ISSUE TITLE
Use The API instead of Scraping?

### ISSUE THREAD

**Issue by scottbisker** [topscoder/nuclei-wordfence-cve#6]
Not sure if you are aware, but Wordfence does provide an API for the Vulnerability Data Feed.  It's free and and would be much easier to maintain the tool.  The API is versioned and well documented to avoid causing breaking changes if the version is updated or the viewable page formats change.  https://www.wordfence.com/intelligence-documentation/v2-accessing-and-consuming-the-vulnerability-data-feed/

Full disclosure: I work for Wordfence.  This came to our attention and would be a perfect use case for the API.

**Comment by topscoder** [comment]
FYI, It's now consuming the API. Although the API missing some information as it seems (like references), it's way better to implement. Thanks again! :)
